title: Project
files: true
pages: false
files:
  fields:
    caption:
      label: Caption
      type: textarea
      buttons:
        - link
        - email
    # videolink:
    #   label: Video ID
    #   type: text
    #   icon: code
    #   help: Youtube ID or Vimeo ID
    # vendor:
    #   label: Vendor
    #   type: radio
    #   default: vimeo
    #   options:
    #     vimeo: Vimeo
    #     youtube: Youtube
    # videostream:
    #   label: Video external stream link (.m3u8)
    #   type: url
    # videoexternal:
    #   label: Video external file link
    #   type: url
    # videofilemp4:
    #   label: Video File (MP4)
    #   type: select
    #   options: videos
    # videofilewebm:
    #   label: Video File (WEBM)
    #   type: select
    #   options: videos
fields:
  previewfiles: 
    type: previewfiles
  prevnext: prevnext
  title:
    label: Title
    type:  text
    width: 3/4
  featured:
    label: Featured image
    type: image
    width: 1/4
  date:
    label: Date
    type:  hidden
    default: today
    format: DD/MM/YYYY
    width: 1/4
  category:
    label: Category
    type: checkboxes
    options: query
    required: true
    columns: 4
    query:
      page: categories
      fetch: visibleChildren
      text: '{{title}}'
      value: '{{uri}}'
  text:
    label: Description
    type: simplemde
  credits:
    label: Credits
    type: structure
    style: table
    fields:
      title:
        label: Title
        type: text
      text:
        label: Text
        type: text
      url:
        label: URL
        type: url
  medias:
    label: Medias
    type: engineer
    fieldsets:
      image:
        label: Image
        fields:
          info:
            label: Image
            type: info
          image:
            type: hero
          # size:
          #   label: Size
          #   type: radio
          #   required: true
          #   default: default
          #   options:
          #     default: Default
          #     small: Small
          #     large: Large
          #     xlarge: X-Large
      # duo:
      #   label: Duo
      #   fields:
      #     info:
      #       label: Duo
      #       type: info
      #     image1:
      #       type: hero
      #       width: 1/2
      #     image2:
      #       type: hero
      #       width: 1/2
      # trio:
      #   label: Trio
      #   fields:
      #     info:
      #       label: Trio
      #       type: info
      #     image1:
      #       type: image
      #       width: 1/3
      #     image2:
      #       type: image
      #       width: 1/3
      #     image3:
      #       type: image
      #       width: 1/3
